### ISSUE TITLE
Add Actions

### ISSUE THREAD

**Issue by LGro** [boschresearch/parameterspace#2]
* [x] install
* [x] formatting
* [x] isort
* [x] mypy
* [x] pylint
* [x] test
* [x] deploy to pypi
* [x] deploy docs

**Comment by dynobo** [comment]
We might also check the existence of the signoff line with [probot](https://probot.github.io/apps/dco/)

**Comment by LGro** [comment]
See #8 for probot signoff check, since AFAIK this is not an action in the sense that we'd integrate it in the pipeline.
