### ISSUE TITLE
two minor hints about typehints

### ISSUE THREAD

**Issue by TaZi-loh** [boschresearch/parameterspace#27]
https://github.com/boschresearch/parameterspace/blob/692292f70a8cf6bef0ed917a602498ea4b2ea3dc/parameterspace/parameters/continuous.py#L25

The type hint should probably read `Tuple[float, float]`

for the cathegorical.py file line 24 the type hint should probably read `Tuple[Any, ...]`.

**Comment by dynobo** [comment]
Fix released with [v0.7.13](https://github.com/boschresearch/parameterspace/releases/tag/v0.7.13). Thanks for reporting, @TaZi-loh :+1:
