### ISSUE TITLE
Docs deployment failed for plugin 'gen-files' option 'module'

### ISSUE THREAD

**Issue by LGro** [boschresearch/parameterspace#53]
https://github.com/boschresearch/parameterspace/actions/runs/3602593325/jobs/6069778628

**Comment by LGro** [comment]
It seems like the docs deployment is failing because of unexpected warnings:
> Run poetry run mike deploy --push --update-aliases v0.7.22 latest
> error: Unexpected log: "WARNING:mkdocs.config:Config value 'plugins': Plugin 'gen-files' option 'module': Unrecognised configuration name: module"

But the comment on the respective [config entry](https://github.com/boschresearch/parameterspace/blob/main/mkdocs.yml#L41-L47) suggests to me that we're actually expecting these warnings. @dynobo, could you confirm that, please? Then we might just look into how to configure mike to expect these warnings as well instead of failing with an error.

**Comment by dynobo** [comment]
I see... locking into a solution.
